pacman -S --needed \
    cmake \
    xdg-utils \
    dust \
    diskus \
    bat \
    fzf \
    lsd \
    lazygit \
    fd \
    ripgrep \
    ripgrep-all \
    skim \
    bacon \
    inetutils \
    openssh \
    starship \
    vivid \
    yazi \
    zoxide \
    zsh \
    zsh-completions \
    zsh-autosuggestions \
    zsh-syntax-highlighting \
