pacman -S --needed \
    cmake \
    xdg-utils \
    dust \
    bat \
    fzf \
    lazygit \
    ripgrep \
    ripgrep-all \
    skim \
    bacon \
    tree-sitter \
    inetutils \
    openssh \
    starship \
    vivid \
    zoxide \
    zsh \
    zsh-completions \
    zsh-autosuggestions \
    zsh-syntax-highlighting \
